# CONFIGURATION GÉNÉRALE DU GATEWAY
server.port=8085
spring.application.name=api-gateway

# ROUTES POUR TOUS LES SERVICES MÉTROPROJET
spring.cloud.gateway.routes[0].id=commande-service
spring.cloud.gateway.routes[0].uri=lb://commande-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/commandes/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.routes[1].filters[0]=AddRequestHeader=X-Internal-Secret, mon-secret-interne

spring.cloud.gateway.routes[2].id=stock-service
spring.cloud.gateway.routes[2].uri=lb://stock-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/stocks/**

spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=lb://user-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[4].id=livraison-service
spring.cloud.gateway.routes[4].uri=lb://livraison-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/livraisons/**
spring.cloud.gateway.routes[4].filters[0]=AddRequestHeader=X-Internal-Secret, mon-secret-interne

spring.cloud.gateway.routes[5].id=review-service
spring.cloud.gateway.routes[5].uri=lb://review-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/reviews/**

# SÉCURITÉ JWT (RESOURCESERVER)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak-global:8080/realms/ecommerce
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak-global:8080/realms/ecommerce/protocol/openid-connect/certs

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
