server.port=8887
spring.application.name=gateway-service

#  Routes vers user-service (via Load Balancer Eureka)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Config Server
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.import-check.enabled=false
spring.config.import=optional:configserver:http://localhost:8888

# ✅ Eureka : port 8762
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ===== Configuration Keycloak (UserWeb_Realm) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/UserWeb_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/UserWeb_Realm/protocol/openid-connect/certs

spring.main.allow-bean-definition-overriding=true

# Centralisation Swagger au niveau de la Gateway
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Définir les sources de documentation pour chaque MS
springdoc.swagger-ui.urls[0].name=User Service (Réactif)
springdoc.swagger-ui.urls[0].url=/users/v3/api-docs

# CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
