spring.application.name=user-service
server.port=8082

# Config Server
spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false

# MySQL R2DBC
spring.r2dbc.url=r2dbc:mysql://localhost:3306/userweb_db
spring.r2dbc.username=root
spring.r2dbc.password=


# Initialisation DB
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/UserWeb_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/UserWeb_Realm/protocol/openid-connect/certs

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/

# Mail Configuration (Gmail exemple)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre.email@gmail.com
spring.mail.password=votre_mot_de_passe_d_application
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Swagger & Monitoring
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
