server.port=8888
spring.application.name=config-service
spring.cloud.config.server.native.search-locations=classpath:/config
spring.profiles.active=native

# Eureka : port 8762
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true