spring.application.name=livraison-service
server.port=8091

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_livraison?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Disable config server (it's failing)
spring.cloud.config.enabled=false

# Welcome message
welcome.message=Bienvenue au service de livraison!

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:6083/realms/ecommerce
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:6083/realms/ecommerce/protocol/openid-connect/certs

# Logging
logging.level.tn.esprit.livraison=DEBUG

internal.secret=my-super-secret-key